package network

import (
	. "github.com/dimpart/demo-go/sdk/common/mkm"
	. "github.com/dimpart/demo-go/sdk/network"
)

type IClientSession interface {
	IBaseSession

	GetStation() Station

	IsAccepted() bool
	SetAccepted(flag bool) bool

	IsReady() bool

	SetSessionKey(key string)
}

/**
 *  Session for Connection
 *  ~~~~~~~~~~~~~~~~~~~~~~
 *
 *  'key' - Session Key
 *          A random string generated by station.
 *          It will be set after handshake success.
 *
 *   'ID' - Local User ID
 *          It will be set before connecting to remote station.
 *          When it's empty, the session state would be 'Default'.
 *
 *   'active' - Session Status
 *          It will be set to True after connected to remote station.
 *          When connection broken, it will be set to False.
 *          Only send message when it's True.
 *
 *   'station' - Remote Station
 *          Station with remote IP &amp; port, its ID will be set
 *          when first handshake responded, and we can trust
 *          all messages from this ID after that.
 */
type ClientSession struct {
	BaseSession

	Station Station

	sessionKey string
	accepted   bool
}
